#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

if [ "${grub_platform}" == "pc" ]; then
	menuentry "Windows 7" {
		insmod part_msdos
		insmod ntfs
		insmod search_fs_uuid
		insmod ntldr
		search --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 D076379A76377FF0
		ntldr /bootmgr
	}
fi

menuentry "System shutdown" {
	echo "System shutting down..."
	halt
}

menuentry "System shutdown" {
	echo "System rebooting now..."
	reboot
}

menuentry "Firmware setup" {
	fwsetup
}
