#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

if [ "${grub_platform}" == "efi" ]; then
	menuentry "Windows 10" {
		insmod part_gpt
		insmod fat
		insmod search_fs_uuid
		insmod chain
		search --fs-uuid --set=root --hint-bios=hd0,gpt2 --hint-efi=hd0,gpt2 --hint-baremetal=ahci0,gpt2 483B-C8C7
		chainloader /EFI/Microsoft/Boot/bootmgfw.efi
	}
fi

menuentry "System shutdown" {
	echo "System shutting down..."
	halt
}

menuentry "System reboot" {
	echo "System rebooting down..."
	reboot
}

menuentry "Firmware setup" {
	fwsetup
}
